<?php 
include 'core/init.php';
include 'includes/overall/header.php' ;

?>
<h1>
<font face="verdana" size="6" color="red">
	<center>
		Hotel & Resort
	</center>
</font>
</h1>
<h2>
<center style="font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, sans-serif">
  <p>Welcome to Malaysia's Wonderland</p>
</center>
</h2>
<head>
	<title>Visual Slideshow generated by VisualSlideshow.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Visual Slideshow, Software For Slideshow, Make Flash Slideshow" />
	<meta name="description" content="Visual Slideshow created with Visual Slideshow, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start VisualSlideShow.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine/css/slideshow.css" media="screen" />
	<style type="text/css">.slideshow a#vlb{display:none}</style>
	<script type="text/javascript" src="engine/js/mootools.js"></script>
	<script type="text/javascript" src="engine/js/visualslideshow.js"></script>
	<!-- End VisualSlideShow.com HEAD section -->
</head>
<body style="background-color:#ffffff">
	<!-- Start VisualSlideShow.com BODY section -->
	<div id="show" class="slideshow">
	<div class="slideshow-images">
<a href="#"><img id="slide-0" src="data/images/2.jpg" alt="2" title="2" /></a>
<a href="#"><img id="slide-1" src="data/images/3.jpg" alt="3" title="3" /></a>
<a href="#"><img id="slide-2" src="data/images/1.jpg" alt="1" title="1" /></a>
</div>
<div class="slideshow-thumbnails">
<ul>
<li><a href="#slide-0"><img src="data/thumbnails/2.jpg" alt="2" /></a></li>
<li><a href="#slide-1"><img src="data/thumbnails/3.jpg" alt="3" /></a></li>
<li><a href="#slide-2"><img src="data/thumbnails/1.jpg" alt="1" /></a></li>
</ul>
</div>
<a id="vlb" href="http://visualslideshow.com">Slideshows Software by VisualSlideshow.com v2.0</a>
	</div>
	<!-- End VisualSlideShow.com BODY section -->
</body>


<?php include 'includes/overall/footer.php' ;?>

